/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.guideme.guideme.player.ui;

import org.guideme.guideme.model.Button;
import org.guideme.guideme.model.Guide;
import org.guideme.guideme.player.CurrentPageChangeEvent;
import org.guideme.guideme.player.CurrentPageChangeListener;
import org.guideme.guideme.player.GuidePlayer;

/**
 *
 * @author
 */
public class PlayerWindow extends javax.swing.JFrame implements CurrentPageChangeListener {

    private GuidePlayer guidePlayer;

    /**
     * Creates new form PlayerWindow
     */
    public PlayerWindow() {
        initComponents();
    }

    /**
     * Starts to play the Guide.
     *
     * @param guide
     */
    public void playGuide(Guide guide) {
        setTitle(guide.getTitle());

        guidePlayer = new GuidePlayer(guide);
        guidePlayer.addCurrentPageChangeListener(this);
        guidePlayer.start();
    }

    /**
     * Updates the window after the current page has changed.
     *
     * @param ev
     */
    @Override
    public void currentPageChanged(CurrentPageChangeEvent ev) {
        textField.setContentType("text/html");
        textField.setText(ev.getCurrentPage().getText());
        // TODO show image, start delay, add buttons etc.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textField = new javax.swing.JTextPane();
        continueButton = new javax.swing.JButton();

        jScrollPane1.setViewportView(textField);

        org.openide.awt.Mnemonics.setLocalizedText(continueButton, org.openide.util.NbBundle.getMessage(PlayerWindow.class, "PlayerWindow.continueButton.text")); // NOI18N
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 299, Short.MAX_VALUE)
                .addComponent(continueButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(continueButton)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        // Just a quick-n-dirty way to layout my ideas.
        Button button = guidePlayer.getCurrentPage().getButtons().get(0);
        guidePlayer.buttonPressed(button);
    }//GEN-LAST:event_continueButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane textField;
    // End of variables declaration//GEN-END:variables

}
