package org.guideme.guideme.filesupport;

import java.awt.event.ActionEvent;
import javax.swing.event.ChangeEvent;

final class RecentGuidesPanel extends javax.swing.JPanel {

    private final RecentGuidesOptionsPanelController controller;

    int getMaxToRemember() {
        return (int) maxGuidesToRememberInput.getValue();
    }

    void setMaxToRemember(int value) {
        maxGuidesToRememberInput.setValue(value);
    }

    RecentGuidesPanel(RecentGuidesOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        maxGuidesToRememberInput.getModel().addChangeListener((ChangeEvent e) -> {
            this.controller.changed();
        });
        clearHistoryButton.addActionListener((ActionEvent e) -> {
            this.controller.clearHistory();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        maxGuidesToRememberInput = new javax.swing.JSpinner();
        clearHistoryButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(RecentGuidesPanel.class, "RecentGuidesPanel.jLabel1.text")); // NOI18N

        maxGuidesToRememberInput.setModel(new javax.swing.SpinnerNumberModel(15, 0, 25, 1));

        org.openide.awt.Mnemonics.setLocalizedText(clearHistoryButton, org.openide.util.NbBundle.getMessage(RecentGuidesPanel.class, "RecentGuidesPanel.clearHistoryButton.text")); // NOI18N
        clearHistoryButton.setToolTipText(org.openide.util.NbBundle.getMessage(RecentGuidesPanel.class, "RecentGuidesPanel.clearHistoryButton.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maxGuidesToRememberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(clearHistoryButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maxGuidesToRememberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearHistoryButton)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearHistoryButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner maxGuidesToRememberInput;
    // End of variables declaration//GEN-END:variables
}
