package org.guideme.guideme.nb.viewer;

import org.guideme.guideme.nb.project.GuideProject;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.Mode;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

@ConvertAsProperties(
        dtd = "-//org.guideme.guideme.nb.viewer//GuidePlayer//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "GuidePlayerTopComponent",
        iconBase="org/guideme/guideme/nb/viewer/resources/book_go.png", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.guideme.guideme.nb.viewer.GuidePlayerTopComponent")
@ActionReference(path = "Menu/Window", position = 10, separatorAfter = 11)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_GuidePlayerAction",
        preferredID = "GuidePlayerTopComponent"
)
@Messages({
    "CTL_GuidePlayerAction=Guide Player",
    "CTL_GuidePlayerTopComponent=Guide Player",
    "HINT_GuidePlayerTopComponent=This is the GuidePlayer window"
})
public final class GuidePlayerTopComponent extends TopComponent {

    private GuideProject guideProject;
    
    static GuidePlayerTopComponent findInstance() {
        return (GuidePlayerTopComponent)WindowManager.getDefault().findTopComponent("GuidePlayerTopComponent");
    }

    public GuidePlayerTopComponent() {
        initComponents();
        setName(Bundle.CTL_GuidePlayerTopComponent());
        setToolTipText(Bundle.HINT_GuidePlayerTopComponent());
    }

    public void loadGuide(GuideProject guideProject) {
        this.guideProject = guideProject;
        setDisplayName(guideProject.getGuideName());
        
        // TODO: Implement play functionality....
        guideTitle.setText(this.guideProject.getGuide().Title);
    }
    
    @Override
    public void open() {
        Mode mode = WindowManager.getDefault().findMode("editor");
        if (mode != null) {
            mode.dockInto(this);
            super.open();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guideTitle = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(guideTitle, org.openide.util.NbBundle.getMessage(GuidePlayerTopComponent.class, "GuidePlayerTopComponent.guideTitle.text")); // NOI18N
        guideTitle.setToolTipText(org.openide.util.NbBundle.getMessage(GuidePlayerTopComponent.class, "GuidePlayerTopComponent.guideTitle.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guideTitle)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guideTitle)
                .addContainerGap(278, Short.MAX_VALUE))
        );

        guideTitle.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(GuidePlayerTopComponent.class, "GuidePlayerTopComponent.guideTitle.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel guideTitle;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
