package org.guideme.guideme.milovana;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.guideme.guideme.model.Guide;

public final class MilovanaDownloadVisualPanel3 extends JPanel {

    private final MilovanaDownloadWizardPanel3 panel;
    /**
     * Creates new form MilovanaHtmlDownloadVisualPanel3
     */
    public MilovanaDownloadVisualPanel3(MilovanaDownloadWizardPanel3 panel) {
        initComponents();
        this.panel = panel;
    }

    @Override
    public String getName() {
        return "Start Download";
    }
    
    void clearProgress() {
        this.progressTextField.setText("");
    }
    
    void addProgress(String text) {
        this.progressTextField.append(text + "\n");
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        progressTextField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        progressTextField.setEditable(false);
        progressTextField.setColumns(20);
        progressTextField.setRows(5);
        jScrollPane1.setViewportView(progressTextField);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel3.class, "MilovanaDownloadVisualPanel3.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea progressTextField;
    // End of variables declaration//GEN-END:variables

}
