package org.guideme.guideme.milovana;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public final class MilovanaDownloadVisualPanel1 extends JPanel implements DocumentListener {

    private final MilovanaDownloadWizardPanel1 panel;

    /**
     * Creates new form MilovanaHtmlDownloadVisualPanel1
     */
    public MilovanaDownloadVisualPanel1(MilovanaDownloadWizardPanel1 panel) {
        initComponents();
        this.panel = panel;
        titleTextField.getDocument().addDocumentListener(this);
    }

    @Override
    public String getName() {
        return "Select Tease";
    }

    public String getTeaseId() {
        return teaseIdTextField.getText();
    }

    private TeaseSummary teaseSummary;

    public TeaseSummary getTeaseSummary() {
        return teaseSummary;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        teaseIdTextField = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        authorTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.jLabel1.text")); // NOI18N

        teaseIdTextField.setText(org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.teaseIdTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(goButton, org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.goButton.text")); // NOI18N
        goButton.setToolTipText(org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.goButton.toolTipText")); // NOI18N
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.jLabel2.text")); // NOI18N

        titleTextField.setEditable(false);
        titleTextField.setText(org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.titleTextField.text")); // NOI18N
        titleTextField.setFocusable(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.jLabel3.text")); // NOI18N

        authorTextField.setEditable(false);
        authorTextField.setText(org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.authorTextField.text")); // NOI18N
        authorTextField.setFocusable(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(MilovanaDownloadVisualPanel1.class, "MilovanaDownloadVisualPanel1.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(teaseIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(goButton)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(titleTextField)
                                    .addComponent(authorTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addContainerGap(133, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(teaseIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        if (getTeaseId() != null && getTeaseId().length() > 0) {
            teaseSummary = new MilovanaDownloader().getSummary(getTeaseId());
            if (teaseSummary != null) {
                titleTextField.setText(teaseSummary.getTitle());
                authorTextField.setText(teaseSummary.getAuthorName());
            } else {
                titleTextField.setText("");
                authorTextField.setText("");                
            }
        } else {
            titleTextField.setText("");
            authorTextField.setText("");
        }
    }//GEN-LAST:event_goButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorTextField;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField teaseIdTextField;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        panel.fireChangeEvent();
        updateUI(e);
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        panel.fireChangeEvent();
        updateUI(e);
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        panel.fireChangeEvent();
        updateUI(e);
    }

    public void updateUI(DocumentEvent e) {
        if (this.titleTextField.getDocument() == e.getDocument()) {
            firePropertyChange("Tease Title", null, this.titleTextField.getText());
        }
    }
}
